### ISSUE TITLE
Auto enable?

### ISSUE THREAD

**Issue by Pfctink** [MinevoltRPG/Trails#14]
I can't seem to find a way to automatically enable this plugin for all players. Am I missing something?

**Comment by alexey-va** [comment]
Check out beta release 1.1b. Set "Use-Permission-For-Trails: true" in the config and give "trails.create-trails" to default group. If you already have a config file this line wont appear there. You can delete config.yml and regen it or insert it manually in General.

**Comment by DrkMatr1984** [comment]
Hey Alexey, just wondering if you've considered this? https://github.com/MinevoltRPG/Trails/pull/15#issuecomment-1319586988

**Comment by alexey-va** [comment]
Added in the latest version
