### ISSUE TITLE
PLEASE make a 1.16 version

### ISSUE THREAD

**Issue by RuofengX** [MinevoltRPG/Trails#2]
The plugin is so nice but it doesn't run in my 1.16.5-paper server, with error log:

> [Trails] Enabling Trails v0.6*
> [10:05:12 INFO]: Trails v0.5 BETA by ccrama is enabled!
> [10:05:12 ERROR]: Error occurred while enabling Trails v0.6 (Is it up to date?)
> java.lang.NullPointerException: Cannot invoke "org.bukkit.Material.name()" because "material" is null
>         at org.bukkit.craftbukkit.v1_16_R3.legacy.CraftLegacy.name(CraftLegacy.java:245) ~[patched_1.16.5.jar:git-Paper-777]
>         at me.ccrama.Trails.Main.createLinks(Main.java:119) ~[?:?]
>         at me.ccrama.Trails.Main.onEnable(Main.java:62) ~[?:?]
>         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-777]
>         at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-777]
>         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-777]
>         at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-777]
>         at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-777]
>         at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594) ~[patched_1.16.5.jar:git-Paper-777]
>         at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-777]
>         at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-777]
>         at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-777]
>         at java.lang.Thread.run(Thread.java:831) [?:?]
> [10:05:12 INFO]: [Trails] Disabling Trails v0.6

I am using [this fork](https://github.com/mancdev-git/Trails), that page doesn't have issue icon.
I really want to get this plugin and I could donate some bucks to it.

**Comment by DrkMatr1984** [comment]
Updated to 1.17+ now! Closing this issue.
