### ISSUE TITLE
Auto recovery

### ISSUE THREAD

**Issue by YKDZ** [MinevoltRPG/Trails#23]
Maybe a trail block can recover reversely step by step if not be step onby player.

**Comment by alexey-va** [comment]
Added in the latest beta version. You can download it here on on github and give it a try. If I wont find any bugs I'll release it on spigot today.

**Comment by alexey-va** [comment]
Released it on spigot. Feel free to request any feature you think will be interesting/useful (coding them is a nice programming practise for me). And consider leaving a review on spigot if you like the plugin!

**Comment by DrkMatr1984** [comment]
🚀🌕
