### ISSUE TITLE
GriefPrevention Error

### ISSUE THREAD

**Issue by hatemabsi** [MinevoltRPG/Trails#29]
I've set up the plugin today and all I've changed is the stick to a blaze_rod for checking trails and made trails work in a specific world.

When someone teleports to that world and walks the console spams this error and no trails are created.

https://pastebin.com/0pnePFHr

I have GriefPrevention v16.18 and Trails v1.5

I'll appreciate any help!

**Comment by alexey-va** [comment]
Does GriefPrevention work in this world? Have you changed anything in GP config?

**Comment by alexey-va** [comment]
https://github.com/MinevoltRPG/Trails/releases/tag/1.5t
Try this version. It should print some info in the console. For some reason the plugin can find GP instance and I cant replicate the issue.

**Comment by hatemabsi** [comment]
Hello alexey! Thanks for the new jar file (that file worked perfectly with no errors)

Just to confirm something; if a player that doesnt have permissions to build in a claim walks in the claim, he cannot create trails right?

**Comment by alexey-va** [comment]
Yes, at least that should be the case. Does it work correctly on your server?

**Comment by hatemabsi** [comment]
Haven't tried it yet! I think it will tho!

**Comment by alexey-va** [comment]
Seems like the problem is fixed. I'll post update on spigot in the near future
